version: '3.8'

services:
  db-service:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db  # default DB that gets created automatically
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  auth-service:
    build:
      context: ./auth-service
    depends_on:
      - db-service
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:password@db-service/auth_db
      SECRET_KEY: mysecretkey
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    ports:
      - "8000:8000"

  orders-service:
    build:
      context: ./orders-service
    depends_on:
      - db-service
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:password@db-service/orders_db
    ports:
      - "8001:8000"

volumes:
  postgres_data:
