name: back end auth pipeline

on:
 push:
   branches:
   - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: check out 
      uses: actions/checkout@v4
    
    - name: current directory
      run: |
        echo $GITHUB_WORKSPACE/
    
    - name: Show current directory contents
      run: |
       echo "Current directory: $GITHUB_WORKSPACE"
       ls -al $GITHUB_WORKSPACE/auth-service
       

    - name: upload auth artifacts
      uses: actions/upload-artifact@v4
      with:
        name: auth-artifacts
        path: auth-service
      
    - name: upload order artifacts
      uses: actions/upload-artifact@v4
      with:
        name: order-artifacts
        path: orders-service

  deploy_auth:
    runs-on: ubuntu-latest
    needs: upload
    steps:
    - name: download auth artifacts
      uses: actions/download-artifact@v4
      with:
        name: auth-artifacts
    
    - name: ssh to vm
      run:
        sshpass -p "${{secrets.PASSWORD}}" scp -o StrictHostKeyChecking=no -r $GITHUB_WORKSPACE/* adminuser@${{secrets.HOST}}:/admin/auth
    