name: back end auth pipeline

on:
 push:
   branches:
   - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: check out 
      uses: actions/checkout@v4
    
    - name: current directory
      run: |
        echo $GITHUB_WORKSPACE/
    
    - name: Show current directory contents
      run: |
       echo "Current directory: $GITHUB_WORKSPACE"
       ls -al $GITHUB_WORKSPACE/auth-service
       

    - name: upload auth artifacts
      uses: actions/upload-artifact@v4
      with:
        name: auth-artifacts
        path: auth-service
      
    - name: upload order artifacts
      uses: actions/upload-artifact@v4
      with:
        name: order-artifacts
        path: orders-service

  deploy_auth:
    runs-on: ubuntu-latest
    needs: upload
    steps:
    - name: download auth artifacts
      uses: actions/download-artifact@v4
      with:
        name: auth-artifacts
        path: ./auth-artifacts
    
    - name: ssh to vm
      run: |
        sshpass -p "${{secrets.PASSWORD}}" ssh -o StrictHostKeyChecking=no adminuser@${{secrets.HOST}} "mkdir -p /home/adminuser/auth"
        sshpass -p "${{secrets.PASSWORD}}" scp -o StrictHostKeyChecking=no -r ./auth-artifacts/* adminuser@${{secrets.HOST}}:/home/adminuser/auth
        sshpass -p "${{ secrets.PASSWORD }}" ssh -o StrictHostKeyChecking=no adminuser@${{ secrets.HOST }} << 'EOF'
        cd /home/adminuser/auth
        sudo apt update
        sudo apt install python3 python3-pip -y
        sudo apt install python3-venv -y
        python3 -m venv venv
        source venv/bin/activate
        pip install --no-cache-dir -r requirements.txt
        export DATABASE_URL="postgresql+asyncpg://postgres:Adminuser123@stylestoreserver.postgres.database.azure.com:5432/auth_db"
        nohup uvicorn main:app --host 0.0.0.0 --port 8000 --reload > /dev/null 2>&1 &
        EOF


  deploy_orders:
    runs-on: ubuntu-latest
    needs: upload
    steps:
    - name: download order artifacts
      uses: actions/download-artifact@v4
      with:
        name: order-artifacts
        path: ./order-artifacts
    
    - name: ssh to vm
      run: |
        sshpass -p "${{secrets.PASSWORD}}" ssh -o StrictHostKeyChecking=no adminuser@${{secrets.ORDER_HOST}} "mkdir -p /home/adminuser/orders"
        sshpass -p "${{secrets.PASSWORD}}" scp -o StrictHostKeyChecking=no -r ./order-artifacts/* adminuser@${{secrets.ORDER_HOST}}:/home/adminuser/orders
        sshpass -p "${{ secrets.PASSWORD }}" ssh -o StrictHostKeyChecking=no adminuser@${{ secrets.ORDER_HOST }} << 'EOF'
        cd /home/adminuser/orders
        sudo apt update
        sudo apt install python3 python3-pip -y
        sudo apt install python3-venv -y
        python3 -m venv venv
        source venv/bin/activate
        pip install --no-cache-dir -r requirements.txt
        export DATABASE_URL="postgresql+asyncpg://postgres:${{ secrets.DB_PASSWORD }}@stylestoreserver.postgres.database.azure.com:5432/auth_db"
        nohup uvicorn main:app --host 0.0.0.0 --port 8000 --reload > /dev/null 2>&1 &
        EOF






