name: back end auth pipeline

on:
 push:
   branches:
   - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: check out 
      uses: actions/checkout@v4
    
    - name: current directory
      run: |
        echo $GITHUB_WORKSPACE/store-backend/auth-service
        echo ls -la $GITHUB_WORKSPACE/store-backend/auth-service

    - name: upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: auth-artifacts
        path: $GITHUB_WORKSPACE/auth-service
      
    - name: upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: order-artifacts
        path: $GITHUB_WORKSPACE/orders-service
